[package]
name = "poptrie"
description = "A pure-rust implementation of poptrie"
homepage = "https://github.com/nicolaskagami/poptrie"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
edition = "2024"
readme = "README.md"

[dependencies]

[dev-dependencies]
proptest = "1.10.0"
